name: calculator_converter
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get: ^4.6.5
  get_it: ^7.2.0
  dio: ^4.0.6
  sizer: ^2.0.15
  dartz: ^0.10.1
  animate_do: ^2.1.0
  flutter_spinkit: ^5.1.0
  flutter_svg_provider: ^1.0.3
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  rxdart: ^0.27.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.2

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/flags/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700